rm -f *.pdf
rm -f *.tex

pandoc additional_considerations/commercial_components_Usage/commercial_components_Usage.md -s -o additional_considerations/commercial_components_Usage/commercial_components_Usage.pdf
pandoc additional_considerations/previously_developed_hardware/previously_developed_hardware.md -s -o additional_considerations/previously_developed_hardware/previously_developed_hardware.pdf
pandoc certification_liaison_process/certification_liaison_process.md -s -o certification_liaison_process/certification_liaison_process.pdf
pandoc configuration_management_process/configuration_management_process.md -s -o configuration_management_process/configuration_management_process.pdf
pandoc hardware_design_lifecycle_data/certification_authority/certification_authority.md -s -o hardware_design_lifecycle_data/certification_authority/certification_authority.pdf
pandoc hardware_design_lifecycle_data/certification_reviews/certification_reviews.md -s -o hardware_design_lifecycle_data/certification_reviews/certification_reviews.pdf
pandoc hardware_design_lifecycle_data/scheduling_of_reviews/scheduling_of_reviews.md -s -o hardware_design_lifecycle_data/scheduling_of_reviews/scheduling_of_reviews.pdf
pandoc hardware_design_process/conceptual_design_process/conceptual_design_process.md -s -o hardware_design_process/conceptual_design_process/conceptual_design_process.pdf
pandoc hardware_design_process/detailed_design_process/detailed_design_process.md -s -o hardware_design_process/detailed_design_process/detailed_design_process.pdf
pandoc hardware_design_process/implementation_process/implementation_process.md -s -o hardware_design_process/implementation_process/implementation_process.pdf
pandoc hardware_design_process/production_transition_process/production_transition_process.md -s -o hardware_design_process/production_transition_process/production_transition_process.pdf
pandoc hardware_design_process/requirements_capture_process/requirements_capture_process.md -s -o hardware_design_process/requirements_capture_process/requirements_capture_process.pdf
pandoc hardware_planning_process/hardware_configuration_management_plan/hardware_configuration_management_plan.md -s -o hardware_planning_process/hardware_configuration_management_plan/hardware_configuration_management_plan.pdf
pandoc hardware_planning_process/hardware_design_plan/hardware_design_plan.md -s -o hardware_planning_process/hardware_design_plan/hardware_design_plan.pdf
pandoc hardware_planning_process/hardware_process_assurance_plan/hardware_process_assurance_plan.md -s -o hardware_planning_process/hardware_process_assurance_plan/hardware_process_assurance_plan.pdf
pandoc hardware_planning_process/hardware_validation_plan/hardware_validation_plan.md -s -o hardware_planning_process/hardware_validation_plan/hardware_validation_plan.pdf
pandoc hardware_planning_process/hardware_verification_plan/hardware_verification_plan.md -s -o hardware_planning_process/hardware_verification_plan/hardware_verification_plan.pdf
pandoc hardware_planning_process/plan_for_hardware_aspects_of_certification/plan_for_hardware_aspects_of_certification.md -s -o hardware_planning_process/plan_for_hardware_aspects_of_certification/plan_for_hardware_aspects_of_certification.pdf
pandoc process_assurance/process_assurance.md -s -o process_assurance/process_assurance.pdf
pandoc validation_and_verification_process/validation_process/validation_process.md -s -o validation_and_verification_process/validation_process/validation_process.pdf
pandoc validation_and_verification_process/verification_process/verification_process.md -s -o validation_and_verification_process/verification_process/verification_process.pdf

pandoc additional_considerations/commercial_components_Usage/commercial_components_Usage.md -s -o additional_considerations/commercial_components_Usage/commercial_components_Usage.tex
pandoc additional_considerations/previously_developed_hardware/previously_developed_hardware.md -s -o additional_considerations/previously_developed_hardware/previously_developed_hardware.tex
pandoc certification_liaison_process/certification_liaison_process.md -s -o certification_liaison_process/certification_liaison_process.tex
pandoc configuration_management_process/configuration_management_process.md -s -o configuration_management_process/configuration_management_process.tex
pandoc hardware_design_lifecycle_data/certification_authority/certification_authority.md -s -o hardware_design_lifecycle_data/certification_authority/certification_authority.tex
pandoc hardware_design_lifecycle_data/certification_reviews/certification_reviews.md -s -o hardware_design_lifecycle_data/certification_reviews/certification_reviews.tex
pandoc hardware_design_lifecycle_data/scheduling_of_reviews/scheduling_of_reviews.md -s -o hardware_design_lifecycle_data/scheduling_of_reviews/scheduling_of_reviews.tex
pandoc hardware_design_process/conceptual_design_process/conceptual_design_process.md -s -o hardware_design_process/conceptual_design_process/conceptual_design_process.tex
pandoc hardware_design_process/detailed_design_process/detailed_design_process.md -s -o hardware_design_process/detailed_design_process/detailed_design_process.tex
pandoc hardware_design_process/implementation_process/implementation_process.md -s -o hardware_design_process/implementation_process/implementation_process.tex
pandoc hardware_design_process/production_transition_process/production_transition_process.md -s -o hardware_design_process/production_transition_process/production_transition_process.tex
pandoc hardware_design_process/requirements_capture_process/requirements_capture_process.md -s -o hardware_design_process/requirements_capture_process/requirements_capture_process.tex
pandoc hardware_planning_process/hardware_configuration_management_plan/hardware_configuration_management_plan.md -s -o hardware_planning_process/hardware_configuration_management_plan/hardware_configuration_management_plan.tex
pandoc hardware_planning_process/hardware_design_plan/hardware_design_plan.md -s -o hardware_planning_process/hardware_design_plan/hardware_design_plan.tex
pandoc hardware_planning_process/hardware_process_assurance_plan/hardware_process_assurance_plan.md -s -o hardware_planning_process/hardware_process_assurance_plan/hardware_process_assurance_plan.tex
pandoc hardware_planning_process/hardware_validation_plan/hardware_validation_plan.md -s -o hardware_planning_process/hardware_validation_plan/hardware_validation_plan.tex
pandoc hardware_planning_process/hardware_verification_plan/hardware_verification_plan.md -s -o hardware_planning_process/hardware_verification_plan/hardware_verification_plan.tex
pandoc hardware_planning_process/plan_for_hardware_aspects_of_certification/plan_for_hardware_aspects_of_certification.md -s -o hardware_planning_process/plan_for_hardware_aspects_of_certification/plan_for_hardware_aspects_of_certification.tex
pandoc process_assurance/process_assurance.md -s -o process_assurance/process_assurance.tex
pandoc validation_and_verification_process/validation_process/validation_process.md -s -o validation_and_verification_process/validation_process/validation_process.tex
pandoc validation_and_verification_process/verification_process/verification_process.md -s -o validation_and_verification_process/verification_process/verification_process.tex
