pandoc configuration_management_records.md -s -o configuration_management_records.pdf
pandoc hardware_accomplishment_summary.md -s -o hardware_accomplishment_summary.pdf
pandoc hardware_archive_standards.md -s -o hardware_archive_standards.pdf
pandoc hardware_configuration_index.md -s -o hardware_configuration_index.pdf
pandoc hardware_configuration_management_plan.md -s -o hardware_configuration_management_plan.pdf
pandoc hardware_design_code_standards.md -s -o hardware_design_code_standards.pdf
pandoc hardware_design_data.md -s -o hardware_design_data.pdf
pandoc hardware_design_plan.md -s -o hardware_design_plan.pdf
pandoc hardware_environment_configuration_index.md -s -o hardware_environment_configuration_index.pdf
pandoc hardware_process_assurance_plan.md -s -o hardware_process_assurance_plan.pdf
pandoc hardware_requirements_document.md -s -o hardware_requirements_document.pdf
pandoc hardware_requirements_standards.md -s -o hardware_requirements_standards.pdf
pandoc hardware_review_procedure.md -s -o hardware_review_procedure.pdf
pandoc hardware_review_results.md -s -o hardware_review_results.pdf
pandoc hardware_software_interface_data.md -s -o hardware_software_interface_data.pdf
pandoc hardware_validation_plan.md -s -o hardware_validation_plan.pdf
pandoc hardware_validation_standards.md -s -o hardware_validation_standards.pdf
pandoc hardware_verification_plan.md -s -o hardware_verification_plan.pdf
pandoc hardware_verification_standards.md -s -o hardware_verification_standards.pdf
pandoc plan_for_hardware_aspects_of_certification.md -s -o plan_for_hardware_aspects_of_certification.pdf
pandoc process_assurance_records.md -s -o process_assurance_records.pdf
pandoc test_cases_and_testbench_for_simulation.md -s -o test_cases_and_testbench_for_simulation.pdf
pandoc test_procedures_for_physical_test.md -s -o test_procedures_for_physical_test.pdf
pandoc test_results_for_simulation_and_physical_test.md -s -o test_results_for_simulation_and_physical_test.pdf
pandoc trace_data.md -s -o trace_data.pdf
