mkdir scope
mkdir normative_references
mkdir terms_and_definitions
mkdir context_of_the_organization
mkdir leadership
mkdir planning
mkdir support
mkdir operation
mkdir performance_evaluation
mkdir improvement

touch scope/scope.md
touch normative_references/normative_references.md
touch terms_and_definitions/terms_and_definitions.md
touch context_of_the_organization/context_of_the_organization.md
touch leadership/leadership.md
touch planning/planning.md
touch support/support.md
touch operation/operation.md
touch performance_evaluation/performance_evaluation.md
touch improvement/improvement.md
