pandoc scope/scope.md -s -o scope/scope.pdf
pandoc normative_references/normative_references.md -s -o normative_references/normative_references.pdf
pandoc terms_and_definitions/terms_and_definitions.md -s -o terms_and_definitions/terms_and_definitions.pdf
pandoc context_of_the_organization/context_of_the_organization.md -s -o context_of_the_organization/context_of_the_organization.pdf
pandoc leadership/leadership.md -s -o leadership/leadership.pdf
pandoc planning/planning.md -s -o planning/planning.pdf
pandoc support/support.md -s -o support/support.pdf
pandoc operation/operation.md -s -o operation/operation.pdf
pandoc performance_evaluation/performance_evaluation.md -s -o performance_evaluation/performance_evaluation.pdf
pandoc improvement/improvement.md -s -o improvement/improvement.pdf
